# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "047lbi9dxswjwz3yp3j1abddcfgywl7dpb6s5k59055kq7gk8p1y";
    x86_64-linux = "189yaq7j9vi510q0rxz17ai5wxknllsh1gl4zdzakcpy9d2f8lf6";
    aarch64-linux = "00ap4h7c7ljxd3llhpxc9w177mygf3hyn9hyy0vwdsisb3g1zcsm";
    x86_64-darwin = "1h2dv0qfc0b9v8139j91l0jq4a2qvhgzcszx5yf1x8cpz6f8cwqf";
    aarch64-darwin = "0nkwpk5hhzy2rjrh8i946k57pfx0hf61g6f32gyypnaa73w9yrdh";
  };

  urlMap = {
    i686-linux = "https://github.com/gernotfeichter/alp/releases/download/1.2.0/alp_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.2.0/alp_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.2.0/alp_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.2.0/alp_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.2.0/alp_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "alp";
  version = "1.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alp $out/bin/alp
  '';

  meta = {
    description = "alp - android-linux-pam";
    homepage = "https://github.com/gernotfeichter/alp";
    license = lib.licenses.gpl2Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
