# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "1j5a27vyd7rc0q7w14f7ibfq6lzhqxh93sgc4rmzhfjd2cd9b0f5";
    x86_64-linux = "1mgss5ggd4byl07c8zxk2hgjvx6xd6whbqpv73a4smbm797mm4wp";
    aarch64-linux = "18j8y801f80hkbp72v3x74cpxwxfnsajqvka8rkjzirhdw0pfqwk";
    x86_64-darwin = "1h589qxdalxxnjvajf5baw9v5921x17wyx4ddhv53s58sy6bnks6";
    aarch64-darwin = "01s4pqqzibzak13hf9bkipjql3a5832y9gsn1zm5rgx0x5kvfwi7";
  };

  urlMap = {
    i686-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.8/alp_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.8/alp_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.8/alp_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.1.8/alp_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.1.8/alp_Darwin_arm64.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "alp";
  version = "1.1.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alp $out/bin/alp
  '';

  system = system;

  meta = {
    description = "alp - android-linux-pam
Alp is a convenient - yet secure (DISCLAIMER: still your risk!) - authentication method that lets you use your android device as a key for your Linux machine.
The idea of alp is, instead of typing a password on the Linux machine, the user only clicks a button on an android device to confirm an authentication/authorisation request.
To make proper use of this, add this to /etc/nixos/configuration.nix: ``` # replace yourusername by your user and optionally add additional users you wanto to use alp for: security.sudo.extraRules = [ {
    users = [ "yourusername" ];
    commands = [ {
      command = "{pkgs.alp}/bin/alp";
      options = [ "SETENV" "NOPASSWD" ];
    } ];
}];
# now choose the pam files you want to modify, e.g. If you like to use alp for sudo and login (as used by lightdm): security.pam.services.sudo.text = pkgs.lib.mkDefault( pkgs.lib.mkBefore(
  ''
  # https://github.com/gernotfeichter/alp
  auth    sufficient      pam_exec.so stdout  ${pkgs.sudo}/bin/sudo ${pkgs.alp}/bin/alp auth

  ''
));
security.pam.services.login.text = pkgs.lib.mkDefault( pkgs.lib.mkBefore(
  ''
  # https://github.com/gernotfeichter/alp
  auth    sufficient      pam_exec.so stdout  ${pkgs.sudo}/bin/sudo ${pkgs.alp}/bin/alp auth

  ''
)); ```";
    homepage = "https://github.com/gernotfeichter/alp";
    license = lib.licenses.gpl2Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
