# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "00r36bixga5n5vw1km057wdy4p5vh074ds9blnw41z97q5m1j4b7";
    x86_64-linux = "08c1pdsfmpi4f4jz8q86p8grcfk5pjcwdsgjqf8h6bxppwb1n1p2";
    aarch64-linux = "0ycif39ybf6n8p54rg1vg0snxgqz7wp4yxjr56v5vb28cd1vrvkz";
    x86_64-darwin = "1d25148ibh6kpc9mg82sm6xiavvi7xhq9sgwii1bp16mrgh0s137";
    aarch64-darwin = "1g0dmp2nlrw8vwwkv5q1ah4qcw6d7y4paw9nlhkf5b6bch80l7qz";
  };

  urlMap = {
    i686-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.16/alp_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.16/alp_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.16/alp_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.1.16/alp_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.1.16/alp_Darwin_arm64.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "alp";
  version = "1.1.16";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alp $out/bin/alp
  '';

  system = system;

  meta = {
    description = "alp - android-linux-pam";
    homepage = "https://github.com/gernotfeichter/alp";
    license = lib.licenses.gpl2Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
